#!/bin/bash

# findUsernameAndHomePath (src): finds the currently logged in user from UW linux environment. If user is not found ${userFound} is set FALSE.
# argument: userSectionPattern
# export: username, userFound
# ignore: sections

username=$(whoami)
sections=$(ls / | egrep ${1})

userFound=FALSE
for section in $sections; do
	if [ -e "/${section}/${username}" ]; then
		homepath="/${section}/${username}"
		userFound=TRUE
	fi
done

