#!/bin/bash

if [ ! ${#} -eq 1 ]; then
  echo "Critical Error: properties file not identified"
  exit 1
fi

if [ ! -e ${1} ]; then
  echo "Critical Error: could not find the properties file"
  exit 1
fi

# convert to linux standard file
dos2unix ${1} > /dev/null 2> /dev/null
script=()

while IFS='' read -r line; do
  egrep '=' <<< "${line}" > /dev/null 2> /dev/null
  if [ ${?} -eq 0 ]; then
    while IFS='=' read -r key value; do
      key=$(echo ${key} | tr '.' '_')
      eval ${key}=\${value}
      script+=(${key})
    done <<< "${line}"
  fi
done < ${1}

for key in "${script[@]}"; do
  eval "${key}"="\$(eval echo "\${"${key}"}")"
done