#!/bin/bash

username=$(whoami)
sections=$(ls / | egrep ^u[0-9]?$)

for section in $sections; do
    if [ -e "/${section}/${username}" ]; then
        homepath="/${section}/${username}"
    fi  
done

setupPath=${homepath}/.MyCS/.settings.properties

if [ ! -e ${setupPath} ]; then
	exit 1
fi

declare -A MyCS_properties

while IFS='=' read -r key value; do
	MyCS_properties["${key}"]="${value}"
done < "${setupPath}"

export MyCS_properties
exit 0
